title: Encuentro Iberoamericano sobre Variabilidad, Sistemas Configurables y Líneas de Producto 2020
description: >-
  Encuentro Iberoamericano sobre Variabilidad, Sistemas Configurables y Líneas de Producto
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://encuentrovariabilidad.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - .github/
  - create_entries.py
  - update_assets.py
  - _config.example.yml
  - workflows.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: es
  show_errors: True

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: 
      enable: true
      default_zoom: 17
      home_coord: 47.37808, 8.53935
      map_provider: "OpenStreetMap.Mapnik"
      markers:
        - icon: "comments"  # https://fontawesome.com/icons?from=io
          coord: 47.37808, 8.53935
          marker_color: "red"
          icon_color: "white"
          description: >-
            A short description

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true
  
  talks:
    # Talk categories
    main_categories:
      - name: Descanso
        color: info
      - name: Talk
        color: success
