title: Encuentro Variabilidad 2020
description: >-
  Encuentro Iberoamericano sobre Variabilidad, Sistemas Configurables y Líneas de Producto
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://encuentrovariabilidad.github.io" # the base hostname & protocol for your site, e.g. https://example.com
theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - create_entries.py

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: es

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Encuentro Iberoamericano 
      # img: ''
      url: 'https://encuentrovariabilidad.github.io/'
    links:
      - name: Programa
        relative_url: /program/
      - name: Charlas
        relative_url: /talks/
      - name: Ponentes
        relative_url: /speakers/
      #- name: Location
      #  relative_url: /location/
      #- name: Previous Editions
      #  menu:
      #    - name: 2020 (current)
      #      disabled: true
      #    - name: 2019
      #      relative_url: /2019/
          

  # Main landing page
  main:
    logo:
       img: 'logo.png'
    links:
      - name: Programa
        relative_url: /program/
      - name: Charlas
        relative_url: /talks/
      - name: Ponentes
        relative_url: /speakers/
      #- name: How to get there
      #  relative_url: /location/
      #- name: Tickets
      #  disabled: true
      #  absolute_url: ''

  # Information boxes
  info_bars:
    - title: Bienvenidos al sitio web del primer encuentro iberoamericano sobre Variabilidad, Sistemas Configurables y Líneas de Producto
      color: primary
      main_only: true
      text: ¡Ya tenemos el programa disponible. Te esperamos!
        
    #- text: This is just some random content for demonstration purposes.
    #  color: warning
    #  pages_only: true

  talks:
    # Talk categories
    main_categories:
      - name: Organización
        color: info
      - name: Charla
        color: success

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # URL of location / room overview page
    url: '/location'

    # Disable links to locations
    hide: false
    map: 
      # show map
      enable: false
      # initial map center point
      home_coord: 47.37808, 8.53935
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Hydda.Full
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17
      # markers for points of interest. As a minimum, each needs a coordinate
      markers:
        - coord: 47.37808, 8.53935
          marker_color: "red"
          # symbol on the marker
          # use any fontawesome symbol name https://fontawesome.com/icons?from=io
          icon: "comments"
          icon_color: "white"
          # (html) description shown above the marker
          description: >-
            <b>HBF</b>
            A short description

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
